### ISSUE TITLE
Getting login expired no matter what

### ISSUE THREAD

**Issue by noahlom** [xXChezyXx/TikTok-AutoUpload#1]
Changed the sessionID 3 times and still getting 

"Error: 'project' Response: {'log_pb': {'impr_id': '2024013010441875C7DE24442E2129345D'}, 'status_code': 8, 'status_msg': 'Login expired'}"

im running: 
python tiktok_autoupload.py -s "sessionid here"  -v "vid.mp4" -t "this is a cool post #fyp #funny"

**Comment by xChezY** [comment]
Can you send me the full output, so I can review the line of my code?
