### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by LyZeoN** [xXChezyXx/TikTok-AutoUpload#3]
The request https://www.tiktok.com/api/v1/web/project/post/?aid=1988 no longer returns anything.
I have a 200 status code response, but no content, which is causing an error.

**Comment by xChezY** [comment]
I have updated my repository. Please note that you now need to have Node.js installed to upload your video. One issue with the current program is that it will attempt to upload the video multiple times until it is successful. If you encounter any issues, please send the error messages.

**Comment by LyZeoN** [comment]
I have two accounts. On the first one, everything works fine, but on the other one, the request returns this:
`"{'log_pb': {'impr_id': ''}, 'status_code': 0, 'status_msg': 'Sent successfully'}"`
therefore, the subsequent request `"https://www.tiktok.com/api/v1/web/project/list/?aid=1988"` returns a list with the correct creationID but without "task".

Both accounts were created in the same way, the second one was created last night.
I wonder if it's because of this request `"https://www.tiktok.com/api/v1/item/create/bulk/"` that TikTok is using, I don't know if it's new.

**Comment by LyZeoN** [comment]
I don't know why, but now everything is working. Thank you very much. 
Enjoy.
