### ISSUE TITLE
KeyError: 'project'

### ISSUE THREAD

**Issue by a1reference** [xXChezyXx/TikTok-AutoUpload#5]
C:\Users\Sam\TikTok-AutoUpload>python tiktok_autoupload.py -s xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -v "C:\Users\Sam\Desktop\TestRun\video.mp4" -t "Gbriish"
Traceback (most recent call last):
  File "C:\Users\Sam\TikTok-AutoUpload\tiktok_autoupload.py", line 285, in <module>
    upload_video(args.sessionid, args.video, args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel)
  File "C:\Users\Sam\TikTok-AutoUpload\tiktok_autoupload.py", line 114, in upload_video
    project_id = r.json()["project"]["project_id"]
KeyError: 'project'

Can someone help me ?
I keep getting this issue

**Comment by xChezY** [comment]
In your line:
`project_id = r.json()["project"]["project_id"]`

replace it with:
`print(r.json())`
`project_id = r.json()["project"]["project_id"]`

and comment the output here, so I can review your json.

**Comment by a1reference** [comment]
Thanks for taking time and checking my problem.

I still get the same error

**Comment by xChezY** [comment]
Alright, found the problem...
Your SessionID is wrong, that is why the program responds with "KeyError: 'project'.
I will add a guide in the README.md

**Comment by a1reference** [comment]
I'm sure my SessionID is right, but I didn't want to share it publicly

**Comment by xChezY** [comment]
A guide is now added in README.md.

If you are sure that your sessionid is correct, try logging out and logging in to Tiktok and get the sessionid again.

There must be something wrong with your sessionid because when I put a wrong sessionid in the program I get the same error output:
```
Traceback (most recent call last):
File "C:\Users\ChezY\Documents\Development\Python\tiktok_autoupload.py", line 296, in <module>
    upload_video(args.sessionid, args.video, args.title, args.schedule, args.comment, args.duet, args.stitch, args.visibility, args.brandorganic, args.brandcontent, args.ailabel, args.proxy)
  File "C:\Users\ChezY\Documents\Development\Python\tiktok_autoupload.py", line 119, in upload_video
    project_id = r.json()["project"]["project_id"]
KeyError: 'project'
```
